### ISSUE TITLE
Support for <div contenteditable>?

### ISSUE THREAD

**Issue by bfontaine** [julianlam/tabIndent.js#11]
Hi,

Currently, tabIndent works only on `textarea` elements, is a support for editable divs planned?

**Comment by julianlam** [comment]
Hello bfontaine,

It is now. This should not be too hard to do.

**Comment by julianlam** [comment]
Looked into implementing it. Unfortunately, there isn't a clear cut way for me to figure out where the cursor is, since `window.getSelection()` doesn't update its values if the selected text is not a range of characters.

Some more research may be required to work around this issue before it can be merged into the mainline.

The branch contenteditable-support contains what I've done so far.
